import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full h-[70px] bg-purple-400">
          Header
        </header>
    
        {children}
        <footer className="w-full h-[70px] bg-purple-400">
          Footer
        </footer>
      </body>
    </html>
  );
}
